### ISSUE TITLE
Pamięci retro

### ISSUE THREAD

**Issue by CCKMik** [jakubfi/ictester#1]
czy było by możliwe testowanie retro pamięci, np takich:
(oprócz 4164 and 41256)

dip:  4416, 4464, 44256, 4116, 4416, 4464, 44256

i z jakimś adapterem
zip 514400az, zip 54400az

itp
??

**Comment by jakubfi** [comment]
Możliwości testera ograniczone są przede wszystkim przez:
* ilość wyprowadzeń (max 24)
* dostępne napięcia zasilania (tylko +5V)
* lokalizację wyprowadzeń +5V i GND

Dla pamięci mieszczących się w tych wymaganiach jest spora szansa. Pozostaje jeszcze kwestia wymagań związanych z odświeżaniem pamięci - to trzeba by sprawdzić już eksperymentalnie.

**Comment by CCKMik** [comment]
na 95%  w/w wymagania są spełnione :)

**Comment by jakubfi** [comment]
Jeśli Twoją intencją w tym zgłoszeniu było poszerzenie możliwości testera o testowanie wspomnianych układów (a nie tylko uzyskanie ogólnej informacji na temat jego możliwości, jak by wynikało z pytania), to odsyłam do [HOWTO](https://github.com/jakubfi/ictester/wiki/How-to-request-support-for-a-new-chip) opisującego jak do tego podejść.

**Comment by CCKMik** [comment]
dodam tylko, że bym kupił złożony komplet, gdy będą obsługiwane w/w scalaki 
:)
